React Router added, button fixed
NakataCode/BooksProject pull request #2
Opened 2023-02-12 18:29 UTC by NakataCode

## Features added:
 - React router added 
 - Home button fixed

2023-02-12 22:42 UTC, heitara requested changes
Не съм прегледал напред, но ще продължа. Ти опитай да подобриш нещата по коментара.

2023-02-12 22:42 UTC, heitara commented on my-app/src/App.tsx
> +      <Route path="book/7" element={<BookPageComponent7 index={6} />} />
Това тук трябва да е динамично - в смисъл, идто да не е записано директно.

2023-02-13 12:54 UTC, NakataCode commented on my-app/src/App.tsx
> +      <Route path="book/7" element={<BookPageComponent7 index={6} />} />
Тук става въпрос да се направи динамичен index-а нали?

2023-03-02 09:50 UTC, heitara commented on my-app/src/BookComponent/BookPageComponent2.tsx
> +import "../App.css";
Добре е css файла да е прилежащ към компонента(да носи неговото име). Ако използваш споделен, той трябва да е в споделен файл. (Такива зависимости като тази са лоши за преизползването на компоненти - понеже после за да го вземеш този компонент, трябва са вземеш и част от App.css)

2023-03-02 09:50 UTC, heitara commented on my-app/src/App.tsx
> +      <Route path="book/7" element={<BookPageComponent7 index={6} />} />
Компонентите с какво се различават? Мисля, че можеш да ги параметризираш. Опитай.

2023-03-02 09:50 UTC, heitara commented on my-app/src/App.tsx
> +      <Route path="/book/:id" element={<BookItemComponent />} />
Тук как подаваш id-то на компонента?

2023-03-02 09:50 UTC, heitara commented on my-app/src/BookComponent/BookItemComponent.tsx
> +}
Това е правилно, но може да се премести в нов файл.

2023-03-02 09:50 UTC, heitara commented on my-app/src/BookComponent/BookItemComponent.tsx
> +  const { id } = useParams<{ id: string }>();
Предполагам, че това ти позволява да вземеш параметъра от router-a. Добре е да проверяваш, че е цяло числи.

2023-03-02 09:50 UTC, heitara commented on my-app/src/BookComponent/BookItemComponent.tsx
> +  };
Това е добро решение. Можеш да проучиш как би станало с Provider и Контекст. На кратко - някъде в основата на йерархията ще трябва да създадеш колекция(речник), в която ще записваш прогреса за всяка книга. Ще имаш хуук, който ще чете (ще взема речника) прогреса за текущата книга и ще сетва новата стойност в речника.за създаването на хуук а позлваш Provider. За четенето Context. Повече инфо тук https://reactjs.org/docs/context.html

Самата имплементация на провайдъра може да използва твоя подход с локал сториджа и да съхранява данните и да ги чете в началото.

2023-03-03 19:43 UTC, NakataCode commented on my-app/src/BookComponent/BookPageComponent2.tsx
> +import "../App.css";
ще направя отеделен файл с името на компонента!

2023-03-03 19:44 UTC, NakataCode commented on my-app/src/BookComponent/BookItemComponent.tsx
> +}
На последният commit е в отделен файл!

2023-03-03 22:54 UTC, NakataCode commented on my-app/src/App.tsx
> +      <Route path="/book/:id" element={<BookItemComponent />} />
id се подава на компонента като prop, когато user-а навигира по страниците чрез URL-а, в случея `book/:id`, това id се третира като URL параметър от самата библиотека. След това самата стойност на този параметър се предава надолу към BookItemComponent като елемент, който всъщост е prop.

2023-03-03 22:55 UTC, NakataCode commented on my-app/src/BookComponent/BookItemComponent.tsx
> +  const { id } = useParams<{ id: string }>();
Ще му сложа една проверка!

2023-03-03 22:57 UTC, NakataCode commented on my-app/src/BookComponent/BookItemComponent.tsx
> +  };
Имах идеята да ползвам context, даже мисля, че се опитах да го направя по едно време с него, но не ми се получи и стигнах до това решение.

2023-03-05 08:04 UTC, heitara commented
Давай да мърджнем, да видим финалния резултат.

2023-03-05 17:42 UTC, merged